### ISSUE TITLE
Are MATD3 agents and MADDPG agents training together in competitive environment?

### ISSUE THREAD

**Issue by 2015211289** [JohannesAck/MATD3implementation#3]
In paper, MATD3 outperforms MADDPG in some envs. Are they trained together or seperate?

**Comment by JohannesAck** [comment]
Hi, thanks for your interest!
I'm not sure if I understand your question correctly, are you asking if all environments are trained together in a multi-task-like setting?

If so, no, the environments are trained completely independently.
